### ISSUE TITLE
mkvmerge crashes on Ctrl+C

### ISSUE THREAD

**Issue by basicmaster** [mbunkus/mkvtoolnix#1173]
When I abort a running muxing process with Ctrl+C, mkvmerge crashes:
```
bla@bla:/daten$ mkvmerge /filme/tshdcut_5201.264 -o /tmp/bla.mkv
mkvmerge v7.8.0 ('River Man') 64bit gebaut am Mar 27 2015 20:38:03
»/filme/tshdcut_5201.264«: Der Demultiplexer für das folgende Format wird benutzt: »AVC/h.264«.
»/filme/tshdcut_5201.264« Spur 0: Das Ausgabemodul für das folgende Format wird benutzt: »AVC/h.264 (unframed)«.
Die Datei »/tmp/bla.mkv« wurde zum Schreiben geöffnet.
»/filme/tshdcut_5201.264« Spur 0: Informationen über das Seitenverhältnis wurden aus den MPEG-4-Layer-10-Videodaten (AVC) extrahiert. Die Anzeigeabmessungen wurden auf 1280/720 gesetzt.
^Crtschritt: 33%
Warnung: Mkvmerge hat ein SIGINT-Signal erhalten (vermutlich, weil der Benutzer Strg+C gedrückt hat). Mkvmerge versucht, die Ausgabedatei ordentlich abzuschließen. Falls Mkvmerge dabei hängen bleibt, müssen Sie es manuell beenden.
Die Datei wird korrigiert, Teil 1/4 … fertig
Die Datei wird korrigiert, Teil 2/4 … fertig
Die Datei wird korrigiert, Teil 3/4 … fertig
Die Datei wird korrigiert, Teil 4/4 … fertig
Fehler: Mkvmerge wurde durch ein Signal unterbrochen (wurde Strg+C gedrückt?)
*** Error in `mkvmerge': double free or corruption (!prev): 0x0000000000ec69f0 ***
Abgebrochen (Speicherabzug geschrieben)
```
The same happens e.g. with M2V files. A larger file, whose muxing can be interrupted easily by hand, seems to be enough.

This happens both with v7.8.0 and the current Git version (using the bundled version of libebml and libmatroska). OS is Ubuntu 14.04 AMD64; the v7.8.0 is from your packet source.

This is the gdb backtrace after SIGINT, while using the Git version:
```
(gdb) signal SIGINT
Continuing with signal SIGINT.

Warning: mkvmerge received a SIGINT (probably because the user pressed Ctrl+C). Trying to sanitize the file. If mkvmerge hangs during this process you'll have to kill it manually.
The file is being fixed, part 1/4... done
The file is being fixed, part 2/4... done
The file is being fixed, part 3/4... done
The file is being fixed, part 4/4... done
Error: mkvmerge was interrupted by a SIGINT (Ctrl+C?)

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000401 in ?? ()
(gdb) bt
#0  0x0000000000000401 in ?? ()
#1  0x00007ffff74e8160 in libebml::EbmlMaster::~EbmlMaster() () from /usr/lib/x86_64-linux-gnu/libebml.so.4
#2  0x00007ffff7764e67 in libmatroska::KaxSegment::~KaxSegment() () from /usr/lib/x86_64-linux-gnu/libmatroska.so.6
#3  0x00000000004aded2 in std::unique_ptr<libmatroska::KaxSegment, std::default_delete<libmatroska::KaxSegment> >::~unique_ptr() ()
#4  0x00007ffff5943259 in __run_exit_handlers (status=2, listp=0x7ffff5cc56c8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#5  0x00007ffff59432a5 in __GI_exit (status=<optimized out>) at exit.c:104
#6  0x000000000060afa1 in mxexit(int) ()
#7  0x00000000006922aa in default_mxerror(unsigned int, std::string const&) ()
#8  0x00000000004a5001 in sighandler(int) ()
#9  <signal handler called>
#10 0x0000000000641661 in mpeg4::p10::avc_es_parser_c::add_bytes(unsigned char*, unsigned long) ()
#11 0x00000000005bcf64 in mpeg4_p10_es_video_packetizer_c::process(std::shared_ptr<packet_t>) ()
#12 0x000000000056def0 in avc_es_reader_c::read(generic_packetizer_c*, bool) ()
#13 0x00000000004aadb0 in main_loop() ()
#14 0x00000000004232e8 in main ()
```

Reading the backtrace, I wonder why regarding libebml and libmatroska, my system lib path is mentioned. configure aborted first, when I did not get the bundled versions of both libs (though I already installed both via apt-get, and also the regarding *-dev packets), so I fetched their submodules and assume(d) that they are used.
But on the other hand, the crash already happens with v7.8.0.

**Comment by mbunkus** [comment]
Thanks for the report.
