### ISSUE TITLE
crash when dropping files from externals apps after removing other files

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1316]
As reported on my blog and via email:

- set up mux settings
- hit »start muxing«
- remove all source files from the mux settings
- drag & drop a file from an external application (e.g. a file manager) onto the now empty mux settings and MKVToolNix GUI crashes

A stack trace contributed by the reporter:

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff5a50ad1 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
    (gdb) bt
    #0  0x00007ffff5a50ad1 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
    #1  0x00007ffff61ea9ce in QDrag::actionChanged(Qt::DropAction) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
    #2  0x00007fffea2e43fe in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
    #3  0x00007fffea2ec369 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
    #4  0x00007fffea2dab3b in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
    #5  0x00007fffea2dbb6b in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
    #6  0x00007ffff5a5222e in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
    #7  0x00007ffff6933c8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
       from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
    #8  0x00007ffff6938e56 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
    #9  0x00007ffff5a29c2d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
    #10 0x00007ffff5a2be07 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
       from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
    #11 0x00007ffff5a76cd3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
    #12 0x00007ffff2cfde04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
    #13 0x00007ffff2cfe048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
    #14 0x00007ffff2cfe0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
    #15 0x00007ffff5a7698c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
       from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
    #16 0x00007ffff5a2896b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
    #17 0x00007ffff5a2f0e1 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
    #18 0x000000000045621a in main (argc=1, argv=0x7fffffffdfd8) at src/mkvtoolnix-gui/mkvtoolnix_gui.cpp:52
    (gdb)

The reporter is using Ubuntu 14.04 64bit. I cannot reproduce this on Arch Linux yet.

**Comment by mbunkus** [comment]
I've installed Ubuntu 14.04 and 15.04. I can reproduce the issue on 14.04, but not on 15.05, nor on my Arch Linux, nor on Windows. Combined with your backtrace I'm judging this to be most likely a bug in Qt itself. I will therefore not invest any more time into this.

**Comment by mbunkus** [comment]
See [here](https://bugreports.qt.io/browse/QTBUG-33057) for a candidate.
