### ISSUE TITLE
Segfault/GUI crash on Ubuntu 14.04.5 w/ Hardware Enablement (mkvtoolnix-gui 9.4.0)

### ISSUE THREAD

**Issue by ProfYaffle** [mbunkus/mkvtoolnix#1775]
**Symptoms**

- Start mkvtoolnix-gui
- Switch off the monitor
- Wait a few seconds
- Switch it back on
- No mkvtoolnix-gui any more, only a disconnected process that has to be killed by hand.

**What I think is happening**

Switching off the monitor is sending a "device disconnected" signal to the X subsystem (xrandr?). Applications built on Qt5 struggle with this, and shoot themselves. Whether this is something you can work around at build time, or whether it's a runtime issue (dependency on installed libraries)... beyond my knowledge now. _It could be that Qt is crashing and that simply takes mkvtoolnix down_, which isn't under your control at all, so apologies in advance if this is nothing to do with you!

It may, however, be related to this:

https://bugreports.qt.io/browse/QTBUG-42985

... but I may be completely wrong with that. It's been known. Often :).

**System**

````text
user@System:~$ uname -a
Linux System 4.4.0-34-generic #53~14.04.1-Ubuntu SMP Wed Jul 27 16:56:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

user@System:~$ lsb_release -a
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:cxx-3.0-amd64:cxx-3.0-noarch:cxx-3.1-amd64:cxx-3.1-noarch:cxx-3.2-amd64:cxx-3.2-noarch:cxx-4.0-amd64:cxx-4.0-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-3.1-amd64:desktop-3.1-noarch:desktop-3.2-amd64:desktop-3.2-noarch:desktop-4.0-amd64:desktop-4.0-noarch:desktop-4.1-amd64:desktop-4.1-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.0-amd64:graphics-3.0-noarch:graphics-3.1-amd64:graphics-3.1-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch:graphics-4.1-amd64:graphics-4.1-noarch:languages-3.2-amd64:languages-3.2-noarch:languages-4.0-amd64:languages-4.0-noarch:languages-4.1-amd64:languages-4.1-noarch:multimedia-3.2-amd64:multimedia-3.2-noarch:multimedia-4.0-amd64:multimedia-4.0-noarch:multimedia-4.1-amd64:multimedia-4.1-noarch:printing-3.2-amd64:printing-3.2-noarch:printing-4.0-amd64:printing-4.0-noarch:printing-4.1-amd64:printing-4.1-noarch:qt4-3.1-amd64:qt4-3.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

user@System:~$ lshw -c video
  *-display               
       description: VGA compatible controller
       product: Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 06
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:33 memory:f7800000-f7bfffff memory:e0000000-efffffff ioport:f000(size=64)

user@System:~$ egrep -i " connected|card detect|primary dev|Setting driver" /var/log/Xorg.0.log
[    70.684] (II) intel(0): Using Kernel Mode Setting driver: i915, version 1.6.0 20151010
````

This is a 14.04 LTS system that's keeping up with the Xenial hardware enablement backports, hence the 4.4.0 kernel. This problem has only begun since the latest updates, so I suspect it's either kernel-related or something to do with the X system updates. The crash is showing in mkvtoolnix, but may not be your issue (I suspect it's actually a Qt issue - see below).

**Application Version**

````text
user@System:~$ apt-cache policy mkvtoolnix-gui*
mkvtoolnix-gui:
  Installed: 9.4.0-0~bunkus01
  Candidate: 9.4.0-0~bunkus01
  Version table: <snip>
mkvtoolnix-gui-dbg:
  Installed: 9.4.0-0~bunkus01
  Candidate: 9.4.0-0~bunkus01
  Version table: <snip>
````

**Stack trace**

````text
user@system:~$ gdb /usr/bin/mkvtoolnix-gui
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/mkvtoolnix-gui...Reading symbols from /usr/lib/debug/.build-id/c4/da2efbc07e20a51eb30dc03e0845c14cd5348c.debug...done.
done.
(gdb) run
Starting program: /usr/bin/mkvtoolnix-gui 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe7319700 (LWP 16344)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5f6bb50 in QScreen::handle() const () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
(gdb) bt
#0  0x00007ffff5f6bb50 in QScreen::handle() const () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#1  0x00007ffff5fa51a1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#2  0x00007ffff5fa3c12 in QRasterPlatformPixmap::resize(int, int) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#3  0x00007ffff5fa1a2c in QPlatformPixmap::create(int, int, QPlatformPixmap::PixelType) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#4  0x00007ffff5f9bbcf in QPixmap::doInit(int, int, int) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#5  0x000000000049af25 in mtx::gui::Util::StyleHelper::verticalGradient (painter=painter@entry=0x7fffffffcc10, spanRect=..., clipRect=..., lightColored=lightColored@entry=false) at src/mkvtoolnix-gui/util/style_helper.cpp:181
#6  0x00000000004d7aaa in mtx::gui::Util::FancyTabWidget::paintEvent (this=<optimised out>) at src/mkvtoolnix-gui/util/fancy_tab_widget.cpp:542
#7  0x00007ffff696f302 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff6933c8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff6938e56 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff5a29c2d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff6969bea in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff696a5bc in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff6969786 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff696a5bc in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff696a434 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff696a434 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff6969786 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff6940233 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff695fe2f in QWidgetPrivate::syncBackingStore() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff696f112 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff6a8013b in QMainWindow::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff6933c8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff6938e56 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff5a29c2d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff5a2be07 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff5a76cd3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff2cfce04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff2cfd048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff2cfd0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff5a7698c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007ffff5a2896b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff5a2f0e1 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x000000000060c367 in mtx::gui::App::run (this=this@entry=0xba7330) at src/mkvtoolnix-gui/app.cpp:493
#34 0x000000000043d3bc in main (argc=1, argv=0x7fffffffe0e8) at src/mkvtoolnix-gui/mkvtoolnix_gui.cpp:47
(gdb) bt full
#0  0x00007ffff5f6bb50 in QScreen::handle() const () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#1  0x00007ffff5fa51a1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#2  0x00007ffff5fa3c12 in QRasterPlatformPixmap::resize(int, int) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#3  0x00007ffff5fa1a2c in QPlatformPixmap::create(int, int, QPlatformPixmap::PixelType) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#4  0x00007ffff5f9bbcf in QPixmap::doInit(int, int, int) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#5  0x000000000049af25 in mtx::gui::Util::StyleHelper::verticalGradient (painter=painter@entry=0x7fffffffcc10, spanRect=..., clipRect=..., lightColored=lightColored@entry=false) at src/mkvtoolnix-gui/util/style_helper.cpp:181
        p = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff62229c0, data = 0x7ffff6222900, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = {d = 0x2a000000047}}
        rect = {x1 = -162906416, y1 = 32767, x2 = -179240960, y2 = 32767}
        key = {static null = {<No data fields>}, d = 0x1216a40}
        keyColor = {cspec = QColor::Invalid, ct = {argb = {alpha = 65535, red = 0, green = 0, blue = 0, pad = 0}, ahsv = {alpha = 65535, hue = 0, saturation = 0, value = 0, pad = 0}, acmyk = {alpha = 65535, cyan = 0, magenta = 0, yellow = 0, black = 0}, ahsl = {
              alpha = 65535, hue = 0, saturation = 0, lightness = 0, pad = 0}, array = {65535, 0, 0, 0, 0}}}
        pixmap = <incomplete type>
#6  0x00000000004d7aaa in mtx::gui::Util::FancyTabWidget::paintEvent (this=<optimised out>) at src/mkvtoolnix-gui/util/fancy_tab_widget.cpp:542
        painter = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff62229c0, data = 0x7ffff6222900, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = {d = 0x124cf10}}
        rect = {x1 = 0, y1 = 0, x2 = 70, y2 = 671}
        light = {cspec = 992, ct = {argb = {alpha = 0, red = 0, green = 24, blue = 0, pad = 0}, ahsv = {alpha = 0, hue = 0, saturation = 24, value = 0, pad = 0}, acmyk = {alpha = 0, cyan = 0, magenta = 24, yellow = 0, black = 0}, ahsl = {alpha = 0, hue = 0, 
              saturation = 24, lightness = 0, pad = 0}, array = {0, 0, 24, 0, 0}}}
#7  0x00007ffff696f302 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#8  0x00007ffff6933c8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#9  0x00007ffff6938e56 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#10 0x00007ffff5a29c2d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#11 0x00007ffff6969bea in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#12 0x00007ffff696a5bc in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#13 0x00007ffff6969786 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#14 0x00007ffff696a5bc in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#15 0x00007ffff696a434 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#16 0x00007ffff696a434 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#17 0x00007ffff6969786 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#18 0x00007ffff6940233 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#19 0x00007ffff695fe2f in QWidgetPrivate::syncBackingStore() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#20 0x00007ffff696f112 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#21 0x00007ffff6a8013b in QMainWindow::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#22 0x00007ffff6933c8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#23 0x00007ffff6938e56 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#24 0x00007ffff5a29c2d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#25 0x00007ffff5a2be07 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#26 0x00007ffff5a76cd3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#27 0x00007ffff2cfce04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#28 0x00007ffff2cfd048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#29 0x00007ffff2cfd0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#30 0x00007ffff5a7698c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#31 0x00007ffff5a2896b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#32 0x00007ffff5a2f0e1 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#33 0x000000000060c367 in mtx::gui::App::run (this=this@entry=0xba7330) at src/mkvtoolnix-gui/app.cpp:493
No locals.
#34 0x000000000043d3bc in main (argc=1, argv=0x7fffffffe0e8) at src/mkvtoolnix-gui/mkvtoolnix_gui.cpp:47
        app = std::unique_ptr<mtx::gui::App> containing 0xba7330
(gdb) 
````

**Comment by mbunkus** [comment]
MKVToolNix doesn't do anything with screen objects. Additionally there are many well-known issues in Qt itself regarding the handling of changing monitor configurations, multiple monitors etc. I'm positive that the issue you're experiencing is a bug in Qt itself. Therefore I'll close this bug.
