### ISSUE TITLE
mkvtoolnix doesn't build with rake-12.0.0 (from ruby-2.4.0)

### ISSUE THREAD

**Issue by uleysky** [mbunkus/mkvtoolnix#1851]
Here is an output of rake:
```
        SCAN pch candidates (total=345, .c=4, .cpp=341)
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
/tmp/save/mkvtoolnix/Rakefile:234:in `block in <top (required)>'
Tasks: TOP => default => src/mkvmerge => src/merge/mkvmerge.o => src/common/common_pch.h.gch
(See full trace by running task with --trace)
```
rake --trace
```
** Invoke config.pch.json (first_time, not_needed)
** Invoke Rakefile (first_time, not_needed)
** Invoke build-config (first_time, not_needed)
** Invoke rake.d/pch.rb (first_time, not_needed)
** Invoke default (first_time)
** Invoke src/mkvmerge (first_time)
** Invoke src/merge/mkvmerge.o (first_time)
** Invoke src/common/common_pch.h.gch (first_time)
** Invoke src/common/common_pch.h (first_time, not_needed)
** Execute src/common/common_pch.h.gch
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
/tmp/save/mkvtoolnix/Rakefile:234:in `block in <top (required)>'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/bin/rake:22:in `load'
/usr/bin/rake:22:in `<main>'
Tasks: TOP => default => src/mkvmerge => src/merge/mkvmerge.o => src/common/common_pch.h.gch
```
Rake from ruby-2.3.3 works fine.

**Comment by mbunkus** [comment]
Thanks. I'll look into it.
