### ISSUE TITLE
configure aborts after finding a too-old version of moc

### ISSUE THREAD

**Issue by Aster89** [mbunkus/mkvtoolnix#1979]
Outputs of `sudo rake` and `sudo rake --trace` (the fist `sudo`, as well as that I use to `./configure`, is necessary since I'm building in `/usr/local/src/mkvtoolnix`):

```
..........$ sudo rake
rake aborted!
build-config not found: please run ./configure
/usr/local/src/mkvtoolnix/rake.d/config.rb:2:in `read_config'
/usr/local/src/mkvtoolnix/Rakefile:38:in `<top (required)>'
(See full trace by running task with --trace)
..........$ sudo rake --trace
rake aborted!
build-config not found: please run ./configure
/usr/local/src/mkvtoolnix/rake.d/config.rb:2:in `read_config'
/usr/local/src/mkvtoolnix/Rakefile:38:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:28:in `load'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:28:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:689:in `raw_load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:94:in `block in load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:93:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:77:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:75:in `run'
/usr/bin/rake:27:in `<main>'
```
I use Linux Mint  18.1 Cinnamon 64-bit

It seems like the `sudo ./configure` step does not create the `build-config` file, as you can see:
```
.......$ ll
totale 1096
drwxr-xr-x 17 root root   4096 mag  7 17:11 ./
drwxr-xr-x 24 root root   4096 mag  7 17:04 ../
drwxr-xr-x  2 root root   4096 mag  7 17:08 ac/
-rw-r--r--  1 root root   9300 mag  7 17:08 AUTHORS
-rwxr-xr-x  1 root root   2402 mag  7 17:08 autogen.sh*
drwxr-xr-x  2 root root   4096 mag  7 17:10 autom4te.cache/
-rw-r--r--  1 root root   3882 mag  7 17:08 build-config.in
-rw-r--r--  1 root root     52 mag  7 17:08 ChangeLog
-rwxr-xr-x  1 root root  43499 mag  7 17:10 config.guess*
-rw-r--r--  1 root root   4944 mag  7 17:10 config.h.in
-rw-r--r--  1 root root  40002 mag  7 17:11 config.log
-rwxr-xr-x  1 root root  36144 mag  7 17:10 config.sub*
-rwxr-xr-x  1 root root 362449 mag  7 17:10 configure*
-rw-r--r--  1 root root   1706 mag  7 17:08 configure.ac
-rw-r--r--  1 root root  18092 mag  7 17:08 COPYING
drwxr-xr-x  4 root root   4096 mag  7 17:08 debian-upstream/
drwxr-xr-x  6 root root   4096 mag  7 17:08 doc/
drwxr-xr-x  3 root root   4096 mag  7 17:08 examples/
drwxr-xr-x  8 root root   4096 mag  7 17:08 .git/
-rw-r--r--  1 root root   1611 mag  7 17:08 .gitignore
-rw-r--r--  1 root root    206 mag  7 17:08 .gitmodules
-rw-r--r--  1 root root   8277 mag  7 17:08 INSTALL
drwxr-xr-x  3 root root   4096 mag  7 17:08 installer/
-rw-r--r--  1 root root   5564 mag  7 17:08 install-sh
drwxr-xr-x 10 root root   4096 mag  7 17:08 lib/
-rwxr-xr-x  1 root root   1801 mag  7 17:08 mkinstalldirs*
-rw-r--r--  1 root root   6558 mag  7 17:08 mkvtoolnix.spec
-rw-r--r--  1 root root 373253 mag  7 17:08 NEWS.md
drwxr-xr-x  3 root root   4096 mag  7 17:08 po/
drwxr-xr-x  2 root root   4096 mag  7 17:08 rake.d/
-rw-r--r--  1 root root  40005 mag  7 17:08 Rakefile
-rw-r--r--  1 root root  13224 mag  7 17:08 README.md
-rw-r--r--  1 root root   3832 mag  7 17:08 README.Windows.md
drwxr-xr-x  7 root root   4096 mag  7 17:08 share/
drwxr-xr-x 13 root root   4096 mag  7 17:08 src/
drwxr-xr-x  4 root root  32768 mag  7 17:08 tests/
drwxr-xr-x  5 root root   4096 mag  7 17:08 tools/
drwxr-xr-x  2 root root   4096 mag  7 17:08 .tx/
```

**Comment by mbunkus** [comment]
Yeah well, if `configure` doesn't create `build-config`, then the output of `rake` is not helpful. The output of `configure` would be helpful instead, as would be the content of `config.log`. Paste the latter to [gist.github.com](https://gist.github.com/) and not directly in the issue as it's quite big.

**Comment by Aster89** [comment]
The `config.log` file is [here](https://gist.github.com/Aster89/cd883d9c3d7ef7b44d221fcbac3ea670), while the output of `sudo ./configure` is the following
```
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc and cc understand -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for ranlib... ranlib
checking for strip... strip
checking for ar... ar
checking for ld... ld
checking for strings... strings
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking for sys/types.h... (cached) yes
checking sys/syscall.h usability... yes
checking sys/syscall.h presence... yes
checking for sys/syscall.h... yes
checking stropts.h usability... yes
checking stropts.h presence... yes
checking for stropts.h... yes
checking for vsscanf... yes
checking for syscall... yes
checking gcc version... 6.2.0
checking for support for the "-std=c++14" flag... -std=gnu++14
checking for support for C++11 feature "initializer lists"... yes
checking for support for C++11 feature "range-based 'for'"... yes
checking for support for C++11 feature "right angle brackets"... yes
checking for support for C++11 feature "'auto' keyword"... yes
checking for support for C++11 feature "lambda functions"... yes
checking for support for C++11 feature "nullptr"... yes
checking for support for C++11 feature "tuples"... yes
checking for support for C++11 feature "alias declarations"... yes
checking for support for C++14 feature "std::make_unique"... yes
checking for support for C++14 feature "digit separators"... yes
checking for support for C++14 feature "binary literals"... yes
checking for support for C++14 feature "generic lambdas"... yes
checking compiler is clang... no
checking whether the byte order is big-endian... no
checking if being compiled with mingw32... no
checking for int64_t... yes
checking for uint64_t... yes
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking for PRId64 and PRIu64... yes
checking iconv.h usability... yes
checking iconv.h presence... yes
checking for iconv.h... yes
checking for iconv... yes
checking for iconv declaration... 
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for nl_langinfo... yes
checking for ogg_sync_init in -logg... yes
checking ogg/ogg.h usability... yes
checking ogg/ogg.h presence... yes
checking for ogg/ogg.h... yes
checking for vorbis_synthesis_init in -lvorbis... yes
checking vorbis/codec.h usability... yes
checking vorbis/codec.h presence... yes
checking for vorbis/codec.h... yes
checking for FLAC__stream_decoder_new in -lFLAC... no
checking for EBML... yes
checking for MATROSKA... yes
checking pugixml.hpp usability... no
checking pugixml.hpp presence... no
checking for pugixml.hpp... no
configure: Using the internal version of the pugixml library
checking nlohmann's json-cpp... no
configure: Using the internal version of nlohmann json-cpp
checking utf8.h usability... no
checking utf8.h presence... no
checking for utf8.h... no
configure: Using the internal version of UTF8-CPP
checking for ZLIB... yes
checking for moc-qt5... no
checking for moc... /usr/bin/moc
checking for the Qt version /usr/bin/moc uses... too old: 4.8.7
```

**Comment by mbunkus** [comment]
Thanks. Just to be sure: does `configure` really end after that line about `moc` being too old?

If so: that shouldn't happen. It should continue with a number of other checks and only disable building the GUIs. I'll look into it.

**Comment by Aster89** [comment]
I confirm: it is the very last line.
